export const tools = [
  // ─── WRITING ───────────────────────────────────────────────
  {
    name: "ChatGPT",
    category: "Writing",
    description: "AI assistant for writing, research and productivity.",
    url: "https://chat.openai.com",
    slug: "chatgpt",
    longDescription:
      "ChatGPT by OpenAI is one of the most widely used AI assistants in the world. It helps with drafting emails, writing essays, brainstorming ideas, answering questions, summarising documents, coding, and much more. GPT-4o supports text, images, and voice.",
    pricing: "Free / $20 per month (Plus) / $25 per month (Pro)",
    pros: [
      "Best-in-class general knowledge and reasoning",
      "Supports images, voice, and file uploads",
      "Huge plugin and GPT ecosystem",
      "Free tier is genuinely useful",
    ],
    cons: [
      "Can hallucinate confidently",
      "Free tier is rate-limited",
      "Privacy concerns with data usage",
    ],
    alternatives: ["claude", "gemini", "perplexity"],
    tags: ["chatbot", "writing", "research", "productivity"],
  },
  {
    name: "Claude",
    category: "Writing",
    description: "AI assistant with long context and thoughtful answers.",
    url: "https://claude.ai",
    slug: "claude",
    longDescription:
      "Claude is Anthropic's AI assistant, known for its long context window (up to 200k tokens), nuanced reasoning, and safe, thoughtful responses. Excellent for summarising long documents, coding, and nuanced writing tasks.",
    pricing: "Free / $20 per month (Pro) / $25 per month (Max)",
    pros: [
      "Industry-leading 200k token context window",
      "Excellent at following complex instructions",
      "Strong safety and honesty focus",
      "Great for long document analysis",
    ],
    cons: [
      "No image generation",
      "Fewer integrations than ChatGPT",
      "Free tier has daily limits",
    ],
    alternatives: ["chatgpt", "gemini", "perplexity"],
    tags: ["chatbot", "writing", "long context", "research"],
  },
  {
    name: "Gemini",
    category: "Writing",
    description: "Google's multimodal AI assistant for writing and research.",
    url: "https://gemini.google.com",
    slug: "gemini",
    longDescription:
      "Gemini is Google's flagship AI assistant, deeply integrated with Google Search, Gmail, Docs, and Drive. Gemini 1.5 Pro offers a 1 million token context window and strong multimodal capabilities for text, images, audio, and video.",
    pricing: "Free / $19.99 per month (Advanced)",
    pros: [
      "Integrated with all Google Workspace apps",
      "Massive 1M token context window",
      "Real-time Google Search access",
      "Strong multimodal support",
    ],
    cons: [
      "Lags behind GPT-4 on some reasoning tasks",
      "Privacy concerns for Google account users",
      "Advanced tier required for best model",
    ],
    alternatives: ["chatgpt", "claude", "perplexity"],
    tags: ["chatbot", "writing", "Google", "multimodal"],
  },
  {
    name: "Jasper",
    category: "Writing",
    description: "AI copywriting platform built for marketing teams.",
    url: "https://jasper.ai",
    slug: "jasper",
    longDescription:
      "Jasper is an AI writing platform purpose-built for marketers. It generates blog posts, ad copy, product descriptions, social media content and more, with brand voice controls and team collaboration features.",
    pricing: "From $39 per month (Creator) / $59 per month (Pro)",
    pros: [
      "Purpose-built templates for marketing use cases",
      "Brand voice and tone controls",
      "Team collaboration features",
      "SEO mode integrations",
    ],
    cons: [
      "Expensive compared to general AI tools",
      "Output still needs human editing",
      "No free tier",
    ],
    alternatives: ["copy-ai", "writesonic", "chatgpt"],
    tags: ["copywriting", "marketing", "content", "SEO"],
  },
  {
    name: "Copy.ai",
    category: "Writing",
    description: "AI writing tool for sales copy and marketing content.",
    url: "https://copy.ai",
    slug: "copy-ai",
    longDescription:
      "Copy.ai helps marketers and sales teams generate copy at scale. It offers 90+ writing templates, a long-form editor, and workflow automation for GTM (go-to-market) teams.",
    pricing: "Free (2,000 words/month) / $36 per month (Pro)",
    pros: [
      "90+ templates for every marketing use case",
      "Generous free tier",
      "Good for sales outreach copy",
      "Workflow automation for teams",
    ],
    cons: [
      "Quality inconsistent on long-form content",
      "Less powerful than ChatGPT for complex tasks",
      "Branding on free plan",
    ],
    alternatives: ["jasper", "writesonic", "chatgpt"],
    tags: ["copywriting", "marketing", "sales", "content"],
  },
  {
    name: "Writesonic",
    category: "Writing",
    description: "AI writer and SEO content platform.",
    url: "https://writesonic.com",
    slug: "writesonic",
    longDescription:
      "Writesonic is an AI writing platform with a built-in SEO focus. It includes Chatsonic (a ChatGPT alternative with web search), an article writer, and Botsonic for building custom chatbots.",
    pricing: "Free (10,000 words) / From $16 per month",
    pros: [
      "Built-in real-time web search via Chatsonic",
      "SEO article writer with keyword targeting",
      "Custom chatbot builder (Botsonic)",
      "Affordable pricing",
    ],
    cons: [
      "UI can feel cluttered",
      "Quality varies by template",
      "Word credit system can be confusing",
    ],
    alternatives: ["jasper", "copy-ai", "chatgpt"],
    tags: ["copywriting", "SEO", "content", "chatbot"],
  },
  // ─── CODING ────────────────────────────────────────────────
  {
    name: "Cursor",
    category: "Coding",
    description: "AI-first code editor built on VS Code.",
    url: "https://cursor.sh",
    slug: "cursor",
    longDescription:
      "Cursor is a VS Code fork with deep AI integration at every level. It can write, refactor, and explain code, answer questions about your entire codebase, auto-fix bugs, and apply multi-file edits from a single prompt.",
    pricing: "Free (2 weeks Pro trial) / $20 per month (Pro)",
    pros: [
      "Best-in-class codebase-aware AI",
      "Multi-file edits from one prompt",
      "Familiar VS Code interface",
      "Supports all major languages and frameworks",
    ],
    cons: [
      "Can be slow on large codebases",
      "Paid tier required for heavy use",
      "AI suggestions sometimes miss context",
    ],
    alternatives: ["github-copilot", "codeium", "replit-ai"],
    tags: ["coding", "IDE", "code editor", "developer tools"],
  },
  {
    name: "GitHub Copilot",
    category: "Coding",
    description: "AI pair programmer by GitHub and OpenAI.",
    url: "https://github.com/features/copilot",
    slug: "github-copilot",
    longDescription:
      "GitHub Copilot suggests code completions and entire functions in real time inside your editor. Powered by OpenAI Codex, it integrates with VS Code, JetBrains, Neovim, and more. Copilot Chat adds conversational AI to your IDE.",
    pricing: "$10 per month / Free for students and open-source maintainers",
    pros: [
      "Deep GitHub integration",
      "Works in VS Code, JetBrains, Neovim",
      "Free for students",
      "Copilot Chat for conversational coding",
    ],
    cons: [
      "Can suggest outdated or insecure code",
      "Less context-aware than Cursor",
      "Requires GitHub account",
    ],
    alternatives: ["cursor", "codeium", "tabnine"],
    tags: ["coding", "autocomplete", "developer tools", "GitHub"],
  },
  {
    name: "Codeium",
    category: "Coding",
    description: "Free AI code completion for 70+ languages.",
    url: "https://codeium.com",
    slug: "codeium",
    longDescription:
      "Codeium offers fast, free AI code completions for over 70 programming languages and integrates with 40+ editors. It focuses on privacy with a no-training-on-your-code policy for enterprise users.",
    pricing: "Free (individual) / $12 per month (Teams) / Enterprise pricing",
    pros: [
      "Completely free for individual use",
      "Supports 70+ languages and 40+ editors",
      "Fast completions with low latency",
      "Strong privacy controls for enterprise",
    ],
    cons: [
      "Less powerful than Copilot on complex tasks",
      "Smaller community and ecosystem",
      "Chat features less polished",
    ],
    alternatives: ["github-copilot", "cursor", "tabnine"],
    tags: ["coding", "autocomplete", "free", "developer tools"],
  },
  {
    name: "Replit AI",
    category: "Coding",
    description: "AI-powered browser coding environment.",
    url: "https://replit.com",
    slug: "replit-ai",
    longDescription:
      "Replit is a browser-based IDE with built-in AI that can generate, explain, and debug code. Replit Agent can build entire apps from a prompt. Great for beginners, students, and quick prototyping without any local setup.",
    pricing: "Free / $7 per month (Core) / $20 per month (Teams)",
    pros: [
      "No setup — runs entirely in the browser",
      "Replit Agent builds full apps from prompts",
      "Great for beginners and education",
      "Built-in hosting and deployment",
    ],
    cons: [
      "Slower than local development",
      "Free tier has limited compute",
      "Not ideal for large production projects",
    ],
    alternatives: ["cursor", "github-copilot", "codeium"],
    tags: ["coding", "browser IDE", "education", "prototyping"],
  },
  {
    name: "Tabnine",
    category: "Coding",
    description: "Privacy-first AI code completion for enterprise teams.",
    url: "https://tabnine.com",
    slug: "tabnine",
    longDescription:
      "Tabnine provides AI code completions with a strong focus on privacy and enterprise compliance. It can run entirely locally on your machine so your code never leaves your environment, making it popular in regulated industries.",
    pricing: "Free / $12 per month (Pro) / Enterprise pricing",
    pros: [
      "Can run fully locally — code never leaves your machine",
      "Strong enterprise compliance features",
      "Supports all major IDEs",
      "Team-trained models on your codebase",
    ],
    cons: [
      "Completions less impressive than Copilot",
      "Slower to adopt new AI model improvements",
      "UI and onboarding could be better",
    ],
    alternatives: ["github-copilot", "codeium", "cursor"],
    tags: ["coding", "autocomplete", "privacy", "enterprise"],
  },

  // ─── IMAGE ─────────────────────────────────────────────────
  {
    name: "Midjourney",
    category: "Image",
    description: "High-quality AI image generation via Discord.",
    url: "https://midjourney.com",
    slug: "midjourney",
    longDescription:
      "Midjourney produces stunning, highly aesthetic images from text prompts. Known for its unique painterly style and consistently high quality output. Operates through Discord and a web interface.",
    pricing: "From $10 per month (Basic) / $30 per month (Standard)",
    pros: [
      "Best aesthetic quality of any image AI",
      "Huge and active community",
      "Consistent, high-quality results",
      "Web interface now available",
    ],
    cons: [
      "No free tier",
      "Primarily Discord-based workflow",
      "Less control over exact compositions",
    ],
    alternatives: ["dall-e", "leonardo-ai", "ideogram"],
    tags: ["image generation", "art", "design", "creative"],
  },
  {
    name: "DALL·E",
    category: "Image",
    description: "OpenAI's image generation model inside ChatGPT.",
    url: "https://openai.com/dall-e-3",
    slug: "dall-e",
    longDescription:
      "DALL·E 3 by OpenAI generates highly accurate images from detailed text prompts. Natively integrated into ChatGPT, making it the most accessible image AI for existing ChatGPT users. Excellent at following complex instructions.",
    pricing: "Included with ChatGPT Plus ($20/month) / API pricing per image",
    pros: [
      "Best at following detailed text prompts",
      "Integrated directly into ChatGPT",
      "API available for developers",
      "Good at text in images",
    ],
    cons: [
      "Less artistic than Midjourney",
      "Requires ChatGPT Plus for unlimited use",
      "Conservative content policy",
    ],
    alternatives: ["midjourney", "leonardo-ai", "flux"],
    tags: ["image generation", "OpenAI", "creative", "design"],
  },
  {
    name: "Leonardo AI",
    category: "Image",
    description: "AI image platform with fine-tuned models for creatives.",
    url: "https://leonardo.ai",
    slug: "leonardo-ai",
    longDescription:
      "Leonardo AI is a creative platform built on Stable Diffusion with a polished UI. It offers fine-tuned models for game assets, concept art, and product design, plus image-to-image, inpainting, and motion features.",
    pricing: "Free (150 tokens/day) / From $10 per month (Apprentice)",
    pros: [
      "Generous free tier",
      "Specialised models for game art and concept design",
      "Image-to-image and inpainting tools",
      "Fast generation speeds",
    ],
    cons: [
      "Token system can feel limiting",
      "Quality inconsistent across models",
      "Interface can be overwhelming for beginners",
    ],
    alternatives: ["midjourney", "dall-e", "ideogram"],
    tags: ["image generation", "game art", "concept art", "creative"],
  },
  {
    name: "Flux",
    category: "Image",
    description: "State-of-the-art open image generation by Black Forest Labs.",
    url: "https://blackforestlabs.ai",
    slug: "flux",
    longDescription:
      "Flux is a family of open image generation models by Black Forest Labs (founded by the original Stable Diffusion team). Flux.1 Pro delivers exceptional photorealism and prompt adherence, available via API and third-party platforms.",
    pricing: "API: ~$0.05 per image / Available via Replicate, fal.ai, and others",
    pros: [
      "Best-in-class photorealism",
      "Excellent prompt adherence",
      "Open weights available",
      "Used by many platforms under the hood",
    ],
    cons: [
      "No official consumer app — requires API or third-party tool",
      "API pricing adds up quickly",
      "Newer, so ecosystem still developing",
    ],
    alternatives: ["midjourney", "dall-e", "leonardo-ai"],
    tags: ["image generation", "open source", "photorealism", "API"],
  },
  {
    name: "Ideogram",
    category: "Image",
    description: "AI image generator with best-in-class text rendering.",
    url: "https://ideogram.ai",
    slug: "ideogram",
    longDescription:
      "Ideogram is an AI image generator that excels at rendering accurate, legible text within images — a notoriously hard problem for image AIs. Great for posters, logos, social graphics, and any design that requires readable text.",
    pricing: "Free (10 slow generations/day) / $7 per month (Basic) / $16 per month (Plus)",
    pros: [
      "Best text-in-image rendering of any AI tool",
      "Great for poster and graphic design",
      "Affordable pricing",
      "Generous free tier",
    ],
    cons: [
      "Less photorealistic than Midjourney or Flux",
      "Smaller community than competitors",
      "Fewer advanced controls",
    ],
    alternatives: ["midjourney", "dall-e", "leonardo-ai"],
    tags: ["image generation", "text rendering", "design", "posters"],
  },

  // ─── VIDEO ─────────────────────────────────────────────────
  {
    name: "Runway",
    category: "Video",
    description: "Professional AI video generation and editing suite.",
    url: "https://runwayml.com",
    slug: "runway",
    longDescription:
      "Runway offers a full suite of AI video tools including Gen-3 Alpha (text-to-video), image-to-video, video-to-video, background removal, and inpainting. Used by professional filmmakers, studios, and content creators.",
    pricing: "Free (125 credits) / $12 per month (Standard) / $28 per month (Pro)",
    pros: [
      "Professional-grade video quality with Gen-3",
      "Full editing suite, not just generation",
      "Used by major film studios",
      "Active development with frequent updates",
    ],
    cons: [
      "Credits run out fast on free tier",
      "Video length limited (up to ~10 seconds per clip)",
      "Expensive for heavy use",
    ],
    alternatives: ["pika", "veo", "heygen"],
    tags: ["video generation", "editing", "creative", "filmmaking"],
  },
  {
    name: "Pika",
    category: "Video",
    description: "AI video creation from text, images, and video clips.",
    url: "https://pika.art",
    slug: "pika",
    longDescription:
      "Pika lets you create and edit videos using AI from text prompts, still images, or existing video clips. Known for its ease of use and fun creative effects like lip sync, sound effects, and the viral pikaffects.",
    pricing: "Free / $8 per month (Basic) / $28 per month (Standard)",
    pros: [
      "Very easy to use",
      "Fun creative effects and lip sync",
      "Good mobile experience",
      "Affordable entry tier",
    ],
    cons: [
      "Less cinematic quality than Runway Gen-3",
      "Short video clips only",
      "Watermark on free tier",
    ],
    alternatives: ["runway", "veo", "synthesia"],
    tags: ["video generation", "text-to-video", "creative", "easy"],
  },
  {
    name: "Synthesia",
    category: "Video",
    description: "AI avatar video creator for training and business content.",
    url: "https://synthesia.io",
    slug: "synthesia",
    longDescription:
      "Synthesia lets you create professional talking-head videos with AI avatars from a text script — no camera, no actors needed. Widely used for corporate training, onboarding videos, and product demos in 140+ languages.",
    pricing: "Free (3 minutes) / $18 per month (Starter) / $64 per month (Creator)",
    pros: [
      "140+ languages and accents",
      "200+ AI avatars or custom avatar",
      "No camera or recording needed",
      "Ideal for corporate training content",
    ],
    cons: [
      "Avatars can feel uncanny or robotic",
      "Not designed for creative or cinematic content",
      "Expensive for high volume",
    ],
    alternatives: ["heygen", "runway", "pika"],
    tags: ["video", "avatars", "business", "training", "multilingual"],
  },
  {
    name: "HeyGen",
    category: "Video",
    description: "AI video platform for personalised avatar and translation videos.",
    url: "https://heygen.com",
    slug: "heygen",
    longDescription:
      "HeyGen creates AI avatar videos from text scripts, with support for video translation that clones your voice and lip-syncs in 40+ languages. Popular for marketing, sales outreach, and content localisation.",
    pricing: "Free (1 credit/month) / $24 per month (Creator) / $72 per month (Business)",
    pros: [
      "Best video translation and dubbing tool",
      "Voice cloning in 40+ languages",
      "Custom avatar from a short video clip",
      "Great for sales and marketing videos",
    ],
    cons: [
      "Very limited free tier",
      "Quality drops on complex scenes",
      "Expensive for scale",
    ],
    alternatives: ["synthesia", "runway", "pika"],
    tags: ["video", "avatars", "translation", "marketing", "voice cloning"],
  },
  {
    name: "Veo",
    category: "Video",
    description: "Google DeepMind's high-quality text-to-video model.",
    url: "https://deepmind.google/technologies/veo",
    slug: "veo",
    longDescription:
      "Veo is Google DeepMind's text-to-video AI model capable of generating high-quality 1080p+ video clips over a minute long. Available through VideoFX and Google's Vertex AI platform for enterprise use.",
    pricing: "Limited access via Google Labs / Vertex AI enterprise pricing",
    pros: [
      "Exceptional video quality and coherence",
      "Long clips (60+ seconds)",
      "Understands cinematic styles and camera movements",
      "Backed by Google DeepMind research",
    ],
    cons: [
      "Very limited public access",
      "No consumer-facing app yet",
      "Enterprise pricing only for API",
    ],
    alternatives: ["runway", "pika", "synthesia"],
    tags: ["video generation", "Google", "text-to-video", "cinematic"],
  },

  // ─── PRODUCTIVITY ──────────────────────────────────────────
  {
    name: "Notion AI",
    category: "Productivity",
    description: "AI writing and summarisation built into Notion.",
    url: "https://notion.so/product/ai",
    slug: "notion-ai",
    longDescription:
      "Notion AI is embedded directly into Notion workspaces and lets you write, summarise, translate, and improve text without leaving your notes. It can also answer questions about content in your workspace.",
    pricing: "$10 per member/month (add-on to any Notion plan)",
    pros: [
      "Deeply integrated into Notion workflow",
      "Summarises pages, meeting notes, and databases",
      "Answers questions about your workspace content",
      "No context switching needed",
    ],
    cons: [
      "Requires a Notion subscription to be useful",
      "Less powerful than standalone AI tools",
      "Add-on cost on top of Notion plans",
    ],
    alternatives: ["grammarly", "chatgpt", "claude"],
    tags: ["writing", "notes", "productivity", "summarisation"],
  },
  {
    name: "Grammarly",
    category: "Productivity",
    description: "AI grammar, style, and clarity checker.",
    url: "https://grammarly.com",
    slug: "grammarly",
    longDescription:
      "Grammarly uses AI to catch grammar mistakes, improve sentence clarity, adjust tone, and detect plagiarism. It works as a browser extension, desktop app, and integrates with Word, Google Docs, and more.",
    pricing: "Free / $12 per month (Premium) / $15 per month (Business)",
    pros: [
      "Works everywhere — browser, Word, Google Docs",
      "Real-time suggestions as you type",
      "Tone detection and goal setting",
      "Plagiarism checker on Premium",
    ],
    cons: [
      "Can over-correct natural writing style",
      "Premium features are expensive",
      "AI writing features less powerful than ChatGPT",
    ],
    alternatives: ["notion-ai", "chatgpt", "writesonic"],
    tags: ["grammar", "editing", "writing", "proofreading"],
  },
  {
    name: "Otter.ai",
    category: "Productivity",
    description: "AI meeting transcription, notes, and summaries.",
    url: "https://otter.ai",
    slug: "otter-ai",
    longDescription:
      "Otter.ai transcribes meetings in real time, generates AI summaries, and extracts action items automatically. It integrates with Zoom, Google Meet, and Microsoft Teams and lets your team search meeting history.",
    pricing: "Free (300 min/month) / $10 per month (Pro) / $20 per month (Business)",
    pros: [
      "Real-time transcription during live meetings",
      "Auto-generated summaries and action items",
      "Integrates with Zoom, Meet, and Teams",
      "Searchable meeting history",
    ],
    cons: [
      "Accuracy drops with accents or crosstalk",
      "Free tier limited to 300 minutes",
      "Transcripts need editing for formal use",
    ],
    alternatives: ["fireflies-ai", "notion-ai", "chatgpt"],
    tags: ["transcription", "meetings", "notes", "productivity"],
  },
  {
    name: "Fireflies AI",
    category: "Productivity",
    description: "AI meeting recorder and searchable knowledge base.",
    url: "https://fireflies.ai",
    slug: "fireflies-ai",
    longDescription:
      "Fireflies.ai records, transcribes, and analyses meetings across all major video conferencing platforms. It builds a searchable knowledge base of all your meetings and can extract topics, sentiments, and action items.",
    pricing: "Free (limited storage) / $10 per month (Pro) / $19 per month (Business)",
    pros: [
      "Works with every major video platform",
      "Searchable meeting database",
      "Sentiment and topic analysis",
      "CRM integrations (Salesforce, HubSpot)",
    ],
    cons: [
      "Free tier has limited storage",
      "Privacy concerns with recording all meetings",
      "Summaries less detailed than Otter.ai",
    ],
    alternatives: ["otter-ai", "notion-ai", "chatgpt"],
    tags: ["transcription", "meetings", "CRM", "productivity", "search"],
  },

  // ─── RESEARCH ──────────────────────────────────────────────
  {
    name: "Perplexity",
    category: "Research",
    description: "AI-powered search engine with cited answers.",
    url: "https://perplexity.ai",
    slug: "perplexity",
    longDescription:
      "Perplexity is an AI-powered search engine that gives direct, well-cited answers to questions by searching the web in real time. Great for research, news, and quickly getting grounded, factual answers.",
    pricing: "Free / $20 per month (Pro)",
    pros: [
      "Real-time web search with cited sources",
      "Much faster than traditional research",
      "Follow-up questions in the same thread",
      "Pro version accesses GPT-4, Claude, and others",
    ],
    cons: [
      "Can still hallucinate despite citations",
      "Not ideal for creative tasks",
      "Pro required for best model access",
    ],
    alternatives: ["chatgpt", "gemini", "claude"],
    tags: ["search", "research", "fact-checking", "citations"],
  },
];

export const CATEGORIES = ["All", ...Array.from(new Set(tools.map((t) => t.category)))];

export const CATEGORY_COLORS = {
  Writing:     { bg: "bg-violet-500/10",  text: "text-violet-400",  border: "border-violet-500/20"  },
  Coding:      { bg: "bg-cyan-500/10",    text: "text-cyan-400",    border: "border-cyan-500/20"    },
  Image:       { bg: "bg-pink-500/10",    text: "text-pink-400",    border: "border-pink-500/20"    },
  Video:       { bg: "bg-orange-500/10",  text: "text-orange-400",  border: "border-orange-500/20"  },
  Research:    { bg: "bg-emerald-500/10", text: "text-emerald-400", border: "border-emerald-500/20" },
  Productivity:{ bg: "bg-yellow-500/10",  text: "text-yellow-400",  border: "border-yellow-500/20"  },
};

export const CATEGORY_ICONS = {
  Writing:      "✍️",
  Coding:       "💻",
  Image:        "🎨",
  Video:        "🎬",
  Research:     "🔬",
  Productivity: "⚡",
};
